import type { Resident } from "./types"

export const allResidents: Resident[] = [
  {
    id: 1,
    name: "Alice Johnson",
    room: "201",
    stabilityScore: 7.8,
    pinkNoiseUsage: "High",
    stabilityGoal: 8.5,
    notes: ["Showing good progress with pink noise usage", "Reported feeling more stable during morning walks"],
    healthMetrics: [
      { name: "Blood Pressure", value: 120, unit: "mmHg" },
      { name: "Heart Rate", value: 72, unit: "bpm" },
      { name: "Sleep Quality", value: 8, unit: "hours" },
    ],
    notifications: [
      {
        id: "1",
        type: "recommendation",
        message: "Consider increasing pink noise usage during afternoon naps",
        timestamp: "2023-05-15T14:30:00Z",
        read: false,
      },
    ],
    pinkNoiseRecommendation: "Increase usage during afternoon naps to improve overall stability",
  },
  {
    id: 2,
    name: "Bob Smith",
    room: "105",
    stabilityScore: 6.5,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 7.0,
    notes: ["Needs encouragement to increase pink noise usage", "Prefers lower volume settings"],
    healthMetrics: [
      { name: "Blood Pressure", value: 130, unit: "mmHg" },
      { name: "Heart Rate", value: 68, unit: "bpm" },
      { name: "Sleep Quality", value: 6, unit: "hours" },
    ],
    notifications: [
      {
        id: "2",
        type: "alert",
        message: "Stability score dropped below goal",
        timestamp: "2023-05-14T09:15:00Z",
        read: true,
      },
    ],
    pinkNoiseRecommendation: "Try using pink noise for 30 minutes before bedtime to improve sleep quality",
  },
  {
    id: 3,
    name: "Carol Davis",
    room: "312",
    stabilityScore: 8.2,
    pinkNoiseUsage: "High",
    stabilityGoal: 8.5,
    notes: ["Consistently using pink noise", "Reports improved balance during daily activities"],
    healthMetrics: [
      { name: "Blood Pressure", value: 118, unit: "mmHg" },
      { name: "Heart Rate", value: 70, unit: "bpm" },
      { name: "Sleep Quality", value: 7.5, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Maintain current usage pattern and monitor for any changes",
  },
  {
    id: 4,
    name: "David Brown",
    room: "118",
    stabilityScore: 5.9,
    pinkNoiseUsage: "Low",
    stabilityGoal: 7.0,
    notes: ["Reluctant to use pink noise", "Experiencing frequent dizzy spells"],
    healthMetrics: [
      { name: "Blood Pressure", value: 140, unit: "mmHg" },
      { name: "Heart Rate", value: 75, unit: "bpm" },
      { name: "Sleep Quality", value: 5, unit: "hours" },
    ],
    notifications: [
      {
        id: "3",
        type: "alert",
        message: "Low pink noise usage detected",
        timestamp: "2023-05-16T10:00:00Z",
        read: false,
      },
    ],
    pinkNoiseRecommendation: "Gradually introduce pink noise during rest periods to improve acceptance",
  },
  {
    id: 5,
    name: "Emma Wilson",
    room: "203",
    stabilityScore: 7.1,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 7.5,
    notes: ["Showing interest in increasing pink noise usage", "Reported improved sleep quality"],
    healthMetrics: [
      { name: "Blood Pressure", value: 125, unit: "mmHg" },
      { name: "Heart Rate", value: 68, unit: "bpm" },
      { name: "Sleep Quality", value: 7, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Consider increasing pink noise usage duration to reach stability goal",
  },
  {
    id: 6,
    name: "Frank Thomas",
    room: "115",
    stabilityScore: 6.8,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 7.5,
    notes: ["Responds well to pink noise during the day", "Needs reminders for evening usage"],
    healthMetrics: [
      { name: "Blood Pressure", value: 128, unit: "mmHg" },
      { name: "Heart Rate", value: 70, unit: "bpm" },
      { name: "Sleep Quality", value: 6.5, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Increase evening pink noise usage to improve overall stability",
  },
  {
    id: 7,
    name: "Grace Lee",
    room: "220",
    stabilityScore: 7.5,
    pinkNoiseUsage: "High",
    stabilityGoal: 8.0,
    notes: ["Enthusiastic about pink noise therapy", "Reports improved focus during daily activities"],
    healthMetrics: [
      { name: "Blood Pressure", value: 122, unit: "mmHg" },
      { name: "Heart Rate", value: 65, unit: "bpm" },
      { name: "Sleep Quality", value: 7.8, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Continue current usage pattern and consider slight increase to reach goal",
  },
  {
    id: 8,
    name: "Henry Garcia",
    room: "308",
    stabilityScore: 6.2,
    pinkNoiseUsage: "Low",
    stabilityGoal: 7.0,
    notes: ["Skeptical about pink noise benefits", "Prefers alternative relaxation methods"],
    healthMetrics: [
      { name: "Blood Pressure", value: 135, unit: "mmHg" },
      { name: "Heart Rate", value: 72, unit: "bpm" },
      { name: "Sleep Quality", value: 5.5, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Introduce pink noise gradually, starting with short sessions during preferred activities",
  },
  {
    id: 9,
    name: "Isabel Martinez",
    room: "112",
    stabilityScore: 7.9,
    pinkNoiseUsage: "High",
    stabilityGoal: 8.5,
    notes: ["Consistent pink noise user", "Reports significant improvement in balance"],
    healthMetrics: [
      { name: "Blood Pressure", value: 118, unit: "mmHg" },
      { name: "Heart Rate", value: 68, unit: "bpm" },
      { name: "Sleep Quality", value: 8, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Maintain current usage and monitor for any changes in effectiveness",
  },
  {
    id: 10,
    name: "Jack Wilson",
    room: "205",
    stabilityScore: 6.7,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 7.5,
    notes: ["Interested in pink noise therapy", "Needs assistance with device operation"],
    healthMetrics: [
      { name: "Blood Pressure", value: 130, unit: "mmHg" },
      { name: "Heart Rate", value: 70, unit: "bpm" },
      { name: "Sleep Quality", value: 6.8, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Provide additional support for device usage and encourage consistent application",
  },
  {
    id: 11,
    name: "Karen Brown",
    room: "317",
    stabilityScore: 7.3,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 8.0,
    notes: ["Enjoys pink noise during reading time", "Requests more information on benefits"],
    healthMetrics: [
      { name: "Blood Pressure", value: 125, unit: "mmHg" },
      { name: "Heart Rate", value: 69, unit: "bpm" },
      { name: "Sleep Quality", value: 7.2, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Increase usage during other daily activities to maximize benefits",
  },
  {
    id: 12,
    name: "Liam Johnson",
    room: "110",
    stabilityScore: 6.0,
    pinkNoiseUsage: "Low",
    stabilityGoal: 7.0,
    notes: ["New to pink noise therapy", "Expresses interest but needs guidance"],
    healthMetrics: [
      { name: "Blood Pressure", value: 132, unit: "mmHg" },
      { name: "Heart Rate", value: 74, unit: "bpm" },
      { name: "Sleep Quality", value: 5.8, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Start with short, regular sessions and gradually increase duration",
  },
  {
    id: 13,
    name: "Mia Taylor",
    room: "222",
    stabilityScore: 8.0,
    pinkNoiseUsage: "High",
    stabilityGoal: 8.5,
    notes: ["Advocates for pink noise among other residents", "Reports improved cognitive function"],
    healthMetrics: [
      { name: "Blood Pressure", value: 120, unit: "mmHg" },
      { name: "Heart Rate", value: 66, unit: "bpm" },
      { name: "Sleep Quality", value: 8.2, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Continue current regimen and consider participating in peer support activities",
  },
  {
    id: 14,
    name: "Noah Anderson",
    room: "305",
    stabilityScore: 7.2,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 7.8,
    notes: ["Uses pink noise primarily for sleep", "Interested in daytime applications"],
    healthMetrics: [
      { name: "Blood Pressure", value: 128, unit: "mmHg" },
      { name: "Heart Rate", value: 71, unit: "bpm" },
      { name: "Sleep Quality", value: 7.5, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Introduce pink noise during daytime rest periods to enhance overall stability",
  },
  {
    id: 15,
    name: "Olivia White",
    room: "119",
    stabilityScore: 6.9,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 7.5,
    notes: ["Combines pink noise with other relaxation techniques", "Reports mixed results"],
    healthMetrics: [
      { name: "Blood Pressure", value: 126, unit: "mmHg" },
      { name: "Heart Rate", value: 69, unit: "bpm" },
      { name: "Sleep Quality", value: 7, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Adjust pink noise usage to complement other techniques for optimal results",
  },
  {
    id: 16,
    name: "Peter Harris",
    room: "210",
    stabilityScore: 7.7,
    pinkNoiseUsage: "High",
    stabilityGoal: 8.2,
    notes: ["Consistent user of pink noise", "Interested in latest research findings"],
    healthMetrics: [
      { name: "Blood Pressure", value: 122, unit: "mmHg" },
      { name: "Heart Rate", value: 67, unit: "bpm" },
      { name: "Sleep Quality", value: 7.8, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Maintain current usage and provide updates on new research developments",
  },
  {
    id: 17,
    name: "Quinn Foster",
    room: "320",
    stabilityScore: 6.3,
    pinkNoiseUsage: "Low",
    stabilityGoal: 7.0,
    notes: ["Prefers nature sounds over pink noise", "Willing to try new approaches"],
    healthMetrics: [
      { name: "Blood Pressure", value: 130, unit: "mmHg" },
      { name: "Heart Rate", value: 73, unit: "bpm" },
      { name: "Sleep Quality", value: 6, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Explore combining pink noise with nature sounds to increase acceptance and usage",
  },
  {
    id: 18,
    name: "Rachel Green",
    room: "108",
    stabilityScore: 7.4,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 8.0,
    notes: ["Uses pink noise during physical therapy sessions", "Reports improved focus"],
    healthMetrics: [
      { name: "Blood Pressure", value: 124, unit: "mmHg" },
      { name: "Heart Rate", value: 70, unit: "bpm" },
      { name: "Sleep Quality", value: 7.3, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Increase usage during other daily activities to enhance overall stability",
  },
  {
    id: 19,
    name: "Samuel Clark",
    room: "225",
    stabilityScore: 6.6,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 7.2,
    notes: ["Recently started using pink noise", "Reports some improvement in sleep quality"],
    healthMetrics: [
      { name: "Blood Pressure", value: 128, unit: "mmHg" },
      { name: "Heart Rate", value: 72, unit: "bpm" },
      { name: "Sleep Quality", value: 6.5, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Gradually increase usage duration to maximize benefits",
  },
  {
    id: 20,
    name: "Tina Rodriguez",
    room: "314",
    stabilityScore: 7.6,
    pinkNoiseUsage: "High",
    stabilityGoal: 8.0,
    notes: ["Enthusiastic about pink noise therapy", "Uses it throughout the day"],
    healthMetrics: [
      { name: "Blood Pressure", value: 120, unit: "mmHg" },
      { name: "Heart Rate", value: 68, unit: "bpm" },
      { name: "Sleep Quality", value: 7.7, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Continue current usage pattern and monitor for any plateau in benefits",
  },
  {
    id: 21,
    name: "Ulysses King",
    room: "106",
    stabilityScore: 6.1,
    pinkNoiseUsage: "Low",
    stabilityGoal: 7.0,
    notes: ["Skeptical about pink noise benefits", "Prefers classical music"],
    healthMetrics: [
      { name: "Blood Pressure", value: 134, unit: "mmHg" },
      { name: "Heart Rate", value: 74, unit: "bpm" },
      { name: "Sleep Quality", value: 5.5, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Introduce pink noise gradually, possibly mixed with classical music",
  },
  {
    id: 22,
    name: "Violet Chang",
    room: "218",
    stabilityScore: 7.8,
    pinkNoiseUsage: "High",
    stabilityGoal: 8.3,
    notes: ["Uses pink noise during meditation", "Reports improved balance"],
    healthMetrics: [
      { name: "Blood Pressure", value: 118, unit: "mmHg" },
      { name: "Heart Rate", value: 65, unit: "bpm" },
      { name: "Sleep Quality", value: 8, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Maintain current usage and consider incorporating into other daily activities",
  },
  {
    id: 23,
    name: "William Turner",
    room: "302",
    stabilityScore: 6.7,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 7.3,
    notes: ["Uses pink noise intermittently", "Interested in learning more about optimal usage"],
    healthMetrics: [
      { name: "Blood Pressure", value: 126, unit: "mmHg" },
      { name: "Heart Rate", value: 71, unit: "bpm" },
      { name: "Sleep Quality", value: 6.8, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Establish a more consistent usage pattern and provide education on benefits",
  },
  {
    id: 24,
    name: "Xena Lawson",
    room: "114",
    stabilityScore: 7.0,
    pinkNoiseUsage: "Medium",
    stabilityGoal: 7.6,
    notes: ["Recently increased pink noise usage", "Reports feeling more energetic"],
    healthMetrics: [
      { name: "Blood Pressure", value: 124, unit: "mmHg" },
      { name: "Heart Rate", value: 69, unit: "bpm" },
      { name: "Sleep Quality", value: 7.2, unit: "hours" },
    ],
    notifications: [],
    pinkNoiseRecommendation: "Continue increasing usage gradually and monitor improvements in stability",
  },
]

